# Bind to interfaces
interface=ens33
interface=ens34
bind-interfaces

# Security
domain-needed
bogus-priv

# Local DNS only
listen-address=127.0.0.1
listen-address=172.16.0.10
listen-address=172.16.0.20

# Split-horizon simulation
localise-queries

# Internal resolution
address=/app.internal.local/172.16.0.20

# External (conceptual override)
address=/app.internal.local/172.16.0.10

# Upstream DNS
server=8.8.8.8
